### ISSUE TITLE
EventBus usage

### ISSUE THREAD

**Issue by xiguajerry** [GuangChen2333/Adequacy#1]
建议你只使用forge的eventbus或nyaevent的其中一个，两者混用很可能因不小心而产生bug。如果你想借用forge的event，可以专门在一个类里监听她并转发为你自己编写的event

**Comment by GuangChen2333** [comment]
收到 tks~

**Comment by GuangChen2333** [comment]
话说我单使用Forge的事件总线会导致一定的性能问题吗（似乎不是我用考虑的）
我最初的设想是将自己的自定义事件丢进自己的事件总线里

**Comment by xiguajerry** [comment]
应该不会。基于反射的EventBus性能都差不多
你可以尝试使用lambda

**Comment by GuangChen2333** [comment]
收到了，思考后写进去，感谢
